//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tekstil_profi_m.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dipEntitie : DbContext
    {
        public dipEntitie()
            : base("name=dipEntitie")
        {
        }
        private static dipEntitie context;
        public static dipEntitie GetContext()
        {
            if (context == null)
                context = new dipEntitie();
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static Users CurrentUser = null;

        public virtual DbSet<Merch> Merch { get; set; }
        public virtual DbSet<Otvetstvenie> Otvetstvenie { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
